# Generated by Django 4.0.3 on 2022-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelin', '0004_refute_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
