# Generated by Django 4.0.3 on 2022-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelin', '0005_argument_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='refute',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
